// <auto-generated />
using FeedbackApp.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FeedbackApp.Migrations
{
    [DbContext(typeof(FeedbackDBContext))]
    [Migration("20190411011740_Added questions")]
    partial class Addedquestions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FeedbackApp.Persistence.Models.FBAnswer", b =>
                {
                    b.Property<int>("KeyID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Answer");

                    b.Property<int>("FBQuestionID");

                    b.Property<int>("UserID");

                    b.HasKey("KeyID");

                    b.HasIndex("FBQuestionID");

                    b.HasIndex("UserID");

                    b.ToTable("FBAnswers");
                });

            modelBuilder.Entity("FeedbackApp.Persistence.Models.FBQuestion", b =>
                {
                    b.Property<int>("KeyID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Question");

                    b.HasKey("KeyID");

                    b.ToTable("FBQuestions");

                    b.HasData(
                        new
                        {
                            KeyID = 1,
                            Question = "How was your exp1?"
                        },
                        new
                        {
                            KeyID = 2,
                            Question = "How was your exp2?"
                        },
                        new
                        {
                            KeyID = 3,
                            Question = "How was your exp3?"
                        },
                        new
                        {
                            KeyID = 4,
                            Question = "How was your exp4?"
                        },
                        new
                        {
                            KeyID = 5,
                            Question = "How was your exp5?"
                        },
                        new
                        {
                            KeyID = 6,
                            Question = "How was your exp6?"
                        },
                        new
                        {
                            KeyID = 7,
                            Question = "How was your exp7?"
                        });
                });

            modelBuilder.Entity("FeedbackApp.Persistence.Models.User", b =>
                {
                    b.Property<int>("KeyID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserName");

                    b.HasKey("KeyID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("FeedbackApp.Persistence.Models.FBAnswer", b =>
                {
                    b.HasOne("FeedbackApp.Persistence.Models.FBQuestion", "FBQuestion")
                        .WithMany()
                        .HasForeignKey("FBQuestionID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FeedbackApp.Persistence.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
